- name: Install nginx on Debian
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create index.html from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reload nginx

- name: Create nginx configuration
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify: Reload nginx

- name: Enable nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload nginx
